#!/usr/bin/env python
# -*- coding: utf-8 -*-

import socket
sock = socket.socket()
sock.connect(('localhost', 9090))
while True:
    a = input()
    sock.send(a.encode('utf-8'))
    data = sock.recv(1024)
    print(data.decode('utf-8'))
sock.close()
