#!/usr/bin/env python
# -*- coding: utf-8 -*-

import socket

sock = socket.socket()
sock.bind(('', 9090))
sock.listen(1)
conn, addr = sock.accept()

print ('connected:', addr)

while True:
    data = conn.recv(1024)
    text = data.decode('utf-8')
    if text:
        print("got text: ", text)
        a = int(text)
        b = a*a
        data = 'Первое число - '+str(a)+' второе число - '+str(b)
        conn.send(data.encode('utf-8'))

conn.close()
